### PR TITLE
Fix published Type Source scenario

### LINKED ISSUE #8119: Fix stale published Source comparison after Type Source view change
## Problem

At current `main` (`d9022f038188c98bccfd2d482534c78e8ce69fb8`), `cd inspect-web && npm test` fails TypeScript compilation in `browser/source-comparison-production.spec.ts`.

The stalled-PDB production scenario added by #8058 still calls `queryTypeSource` with seven arguments and reads `provider`, `text`, `pdbSourceLimitation`, and `url` directly from `BrowserTypeCodeView`. The contract introduced by #8065 requires an eighth `view` argument and returns a discriminated union.

Observed errors:

```text
browser/source-comparison-production.spec.ts(86,39): error TS2554: Expected 8 arguments, but got 7.
browser/source-comparison-production.spec.ts(122,39): error TS2339: Property 'provider' does not exist on type 'BrowserTypeCodeView'.
browser/source-comparison-production.spec.ts(123,39): error TS2339: Property 'text' does not exist on type 'BrowserTypeCodeView'.
browser/source-comparison-production.spec.ts(125,39): error TS2339: Property 'pdbSourceLimitation' does not exist on type 'BrowserTypeCodeView'.
browser/source-comparison-production.spec.ts(127,39): error TS2339: Property 'url' does not exist on type 'BrowserTypeCodeView'.
```

## Expected repair

Pass `"source"` as the eighth argument and narrow the successful value to the Source variant before asserting Source-specific fields.

This currently blocks post-integration validation for #8051.

### PR DESCRIPTION
**Pull request by richlander**
Build robust, capable Source inspection by keeping the published production
scenario aligned with the typed Browser Type Source contract.

Closes #8119.

## Demo

The stalled-PDB production scenario now requests the explicit Source view and
narrows the returned code-view union before reading Source-only evidence:

```ts
const result = await source.queryTypeSource(
  operationId, packageId, version, framework, assembly, type, "[]", "source",
);

if (result.value?.kind !== "source")
  throw new Error("Expected a decompiled type source code view.");
```

This restores compilation of the real published Firefox/Wasm scenario that
verifies `System.Text.Json` falls back to decompilation before the deliberately
stalled PDB response completes.

## Design and boundaries

The normative owner is
`docs/design/type-api-declarations.md#production-adoption-and-rendering`:
Browser Type Source is an explicit code-view selection whose result is a
discriminated Source/API-declarations union. The generated Source facade is the
adjacent wire contract; `source-comparison-production.spec.ts` is the
production-host consumer.

No open PR changes
`inspect-web/browser/source-comparison-production.spec.ts`; #8051 does not
include it. This is a test-contract repair only and changes no product behavior,
dependencies, rendering, or platform support.

The user explicitly requested review immediately after push, so round 1 may run
in parallel with `ci-required` under the repository's user-directed workflow
adjustment.

## Validation

- `npm run typecheck:authored` passed.
- `npx oxlint --no-ignore --disable-nested-config
  browser/source-comparison-production.spec.ts` passed.
- `npx playwright test --config playwright.source-comparison.config.ts --list`
  discovered all 3 production scenarios.
- `npm test` passed TypeScript compilation and 1,945 Node tests; 4 unrelated
  bundler-input audit assertions in `test/toolchain.test.ts` failed after
  compilation.

### CODE REVIEW

**Comment by richlander** [comment]
Round 1 reconciliation — 1 pushed candidate, 1 usable review, 0 accepted
findings.

GPT-5.6 Sol reviewed exact head
`ce9e483622c40d431a699e9bae6a4bdcb677e76d` against base
`d203a7af3dd044eadabfb6e837e6c062535eeb04` and returned **CLEAN**.

The review verified the one-file repair against
`docs/design/type-api-declarations.md#production-adoption-and-rendering` and
the generated Source facade contract. The production call now supplies the
explicit `source` view and narrows the `BrowserTypeCodeView` discriminator
before reading Source-only fields. No finding was dismissed and no author
change is required.

The user explicitly requested immediate review, so this round ran in parallel
with `ci-required`. The reviewed head is unchanged; final readiness remains
subject to successful current-head `ci-required` and live mergeability.
