### PR TITLE
Retain platform supply comparison correspondence

### PR DESCRIPTION
**Pull request by richlander**
This advances dotnet-inspect's package architecture toward a robust
PackageHouse facade by giving the existing platform package-supply policy an
owner-issued join currency.

## Demo

Before, a consumer could retain only the value-shaped `PlatformSupply`:

```csharp
PlatformSupply supply = PlatformPrunePolicy.Decide(inventory, coordinate);
```

That value did not establish which inventory and coordinate comparison
produced it. The policy can now issue correspondence directly:

```csharp
PlatformSupplyReceipt receipt =
    PlatformPrunePolicy.Evaluate(inventory, coordinate);

Assert.Same(inventory, receipt.Inventory);
Assert.Same(coordinate, receipt.Coordinate);
Assert.True(receipt.Supply.DelegatesToPlatform);
```

The existing `Decide` API remains the convenience projection for consumers
that need only the supply value.

## Summary

- add resource-free `PlatformSupplyReceipt` evidence binding the exact
  `PlatformPruneInventory`, `PackageCoordinate`, and computed `PlatformSupply`;
- preserve existing `PlatformPrunePolicy.Decide` behavior through
  `Evaluate(...).Supply`;
- gate both entry-present and absent-entry correspondence, including equal
  supply values from distinct comparisons; and
- update the policy owner document with the receipt contract and gates.

This slice does not implement PackageHouse, reinterpret platform target
identity, or identify a platform assembly. It supplies the focused policy
receipt that #6433 needs before PackageHouse can retain pruning correspondence.

## Validation

```text
dotnet run --project tests/DotnetInspector.Services.Tests -c Release -- \
  --filter-class '*PlatformPrunePolicyTests'
```

11 passed.

```text
npx markdownlint-cli docs/design/platform-package-supply-policy.md
```

Passed.

### CODE REVIEW

**Comment by richlander** [comment]
Failure recovery: the original head failed on stale artifact-namespace defects already fixed by #6434 and #6447. Merged current main and pushed replacement head `ad9f4a40322109dd71d413ea9bb3cb4f5cc68f5e`; the focused PlatformPrunePolicy suite remains green (11/11). Round eligibility restarts at this head.

**Comment by richlander** [comment]
Round 1 review is clean at exact head `ad9f4a40322109dd71d413ea9bb3cb4f5cc68f5e`. GPT-6 Astra found no qualifying correctness, reliability, security, or contract findings. The normative owner remains `docs/design/platform-package-supply-policy.md`: the receipt retains the exact inventory, coordinate, and supply comparison while delegation remains exclusive to `Subsumed`. Current-head `ci-required` completed successfully.
