### ISSUE TITLE
CS0029/CS0173: nint/nuint join arms render bare (SameWidth null-width skips the reinterpret)

### ISSUE THREAD

**Issue by richlander** [richlander/dotnet-inspect#2334]
## Summary

`TryCoerceJoinArm`'s cross-signedness reinterpret branch is gated on `TypeFamilies.SameWidth(...)`, but `SameWidth` returns `false` for the platform-sized integers `nint`/`nuint` because `TypeFamilies.Width()` deliberately returns `null` for them. As a result a `nuint` arm at an `nint` join (or vice-versa) receives **no coercion** and renders bare, which does not compile (`CS0029`/`CS0173` — no implicit conversion between `nint` and `nuint`).

## Location

`src/ILInspector.Decompiler/Pipeline/Ir/CSharpPrinter.Numerics.cs` — `TryCoerceJoinArm` cross-signedness branch:

```csharp
if (target is { } numericTarget
    && TypeFamilies.NeedsNumericCast(EffectiveType(arm), numericTarget)
    && TypeFamilies.SameWidth(EffectiveType(arm), numericTarget))   // <-- false for nint/nuint
{
    ...
}
```

`TypeFamilies.Width()` returns `null` for `IntPtr`/`UIntPtr` (platform width unknown), so `SameWidth(nuint, nint) == false`; the branch is skipped and `TryCoerceJoinArm` returns `null`.

## Reproduced (decompiler product path, synthetic IR)

- Conditional `MergedType = nuint`, `c ? u : i` with `u: nuint`, `i: nint`.
- Probe printed: `needs=True sameWidth=False`.
- Rendered output: `c ? u : i` (bare).
- Compiler proof: `error CS0029: Cannot implicitly convert type 'nint' to 'nuint'`.

## Correct shape

```csharp
c ? u : (nuint)i
```
and, inside a checked region, the cast should be checked-safe (`unchecked((nuint)i)`).

## Suggested direction

`nint`↔`nuint` is a same-(platform-)width cross-signedness reinterpret exactly like the fixed-width sibling casts this branch already handles. Either treat platform-width pairs as same-width for this reinterpret (they always share a width at runtime), or add a dedicated native-int cross-signedness arm. Any cast added inside a checked region must route through `CheckedSafeCast` (`CheckedConversionCanThrow` currently answers `true` for platform-width — the safe direction).

## Provenance

- **Pre-existing**, not a regression: this `NeedsNumericCast && SameWidth` branch was introduced by #2310 and is byte-identical on `origin/main`; #2313 only reformats it.
- Found independently by **both** adversarial reviewers of #2313 (GPT-5.5 and Gemini 3.1 Pro); GPT-5.5 reproduced it through the decompiler product path.
- Relates to the umbrella #2095.
- Reachability on the real corpus is unverified (native-int conditional joins are rare); the code-path and compile failure are proven.
