### ISSUE TITLE
ReturnToSender drops required abstract indexer overrides from compile-back shells

### ISSUE THREAD

**Issue by richlander** [richlander/dotnet-inspect#4231]
## Problem

ReturnToSender drops a required derived indexer override while retaining its
base abstract indexer. The resulting shell cannot compile.

```csharp
public abstract class Base { public abstract int this[int index] { get; } }
public class Derived : Base
{
    public override int this[int index] => index;
    public int Call() => this[1];
}
```

With the default `Cluster` / `Selected` compile-back request for `Derived.Call`,
the shell contains `Base.this[int]` but omits `Derived.this[int]` and reports:

```text
RecompileFail: CS0534: 'Derived' does not implement inherited abstract member 'Base.this[int].get'
```

The drop occurs in
`tools/DecompilerHarness/ReturnToSenderTypePlanner.cs`, where properties with
parameters are skipped. No planning diagnostic identifies the lost required
override.

## Evidence

The same fixture and command produce byte-identical output at #4073 base
`ce9544d83084d8ac8b56f5f962d32170e49cf20a` and head
`d73832a06946590d876913c86a10ef0d32f28e7b`; this is pre-existing, not
introduced by #4073.

Existing #4073 coverage uses a `Call` body that does not reference the indexer,
so it does not take the required-member path that exposes the mismatch.

## Expected

Retain the required derived indexer override when its abstract base declaration
is reconstructed, or fail closed with a specific planning diagnostic before
producing an uncompilable shell.
