### ISSUE TITLE
Fix stale published Source comparison after Type Source view change

### ISSUE THREAD

**Issue by richlander** [richlander/dotnet-inspect#8119]
## Problem

At current `main` (`d9022f038188c98bccfd2d482534c78e8ce69fb8`), `cd inspect-web && npm test` fails TypeScript compilation in `browser/source-comparison-production.spec.ts`.

The stalled-PDB production scenario added by #8058 still calls `queryTypeSource` with seven arguments and reads `provider`, `text`, `pdbSourceLimitation`, and `url` directly from `BrowserTypeCodeView`. The contract introduced by #8065 requires an eighth `view` argument and returns a discriminated union.

Observed errors:

```text
browser/source-comparison-production.spec.ts(86,39): error TS2554: Expected 8 arguments, but got 7.
browser/source-comparison-production.spec.ts(122,39): error TS2339: Property 'provider' does not exist on type 'BrowserTypeCodeView'.
browser/source-comparison-production.spec.ts(123,39): error TS2339: Property 'text' does not exist on type 'BrowserTypeCodeView'.
browser/source-comparison-production.spec.ts(125,39): error TS2339: Property 'pdbSourceLimitation' does not exist on type 'BrowserTypeCodeView'.
browser/source-comparison-production.spec.ts(127,39): error TS2339: Property 'url' does not exist on type 'BrowserTypeCodeView'.
```

## Expected repair

Pass `"source"` as the eighth argument and narrow the successful value to the Source variant before asserting Source-specific fields.

This currently blocks post-integration validation for #8051.
