### PR TITLE
RTS: reconstruct multi-member external explicit-interface methods (#3112, Increment 2)

### PR DESCRIPTION
**Pull request by richlander**
- Advances #3112 (Increment 2 of a stacked pair; Increment 1 was #3222)
- Changes RTS explicit-interface reconstruction for **multi-member external/BCL**
  interfaces (harness-only; product output unchanged)
- Evidence revision: `15e260fa`

## Change

> Should we accept this harness change?

**Conclusion:** **PASS** — Increment 1 (#3222) taught RTS to reconstruct a
**single-member** external explicit-interface method as a real explicit
implementation (ContextFail → Exact), but declined every **multi-member**
external interface (`System.IConvertible`, `System.ComponentModel.ICustomTypeDescriptor`, …)
to the sanitized `ContextFail` floor: naming the interface in the base list forces
the reconstructed type to satisfy the interface's *entire* required surface
(CS0535), and Increment 1 only supplied the single target member. This change
reconstructs the requested target member with its real body **and synthesizes a
`throw null` explicit-interface stub for every other required member**, so the
full surface is satisfied and the target round-trips **Exact**. The engagement is
floor-first and atomic: it engages only when every required member is confidently
spellable, otherwise it declines the whole interface to the pre-fix sanitized
shape — so no `RecompileFail` regression is introduced.

### Reconstructed render (Original → Before → After → Fully raised)

Target: `Convertible System.IConvertible.ToBoolean(IFormatProvider) instance`

**Original** (authoritative anchor — the explicit-interface member the
reconstruction must round-trip; fixture C#):

```csharp
public sealed class Convertible : IConvertible
{
    bool IConvertible.ToBoolean(IFormatProvider provider) => false;
    // + the other 16 IConvertible members (GetTypeCode, ToByte, ToChar, …)
}
```

**Before** (emitted C# at base `ee13d4e2` + verdict): the multi-member external
interface declines to the sanitized floor — `IConvertible` is dropped from the
base list and the dotted member name is decomposed to an underscore-joined plain
method, so the recompiled assembly no longer contains an explicit
`IConvertible.ToBoolean` to opcode-compare:

```csharp
#pragma warning disable
using System;
public sealed class Convertible
{
    bool System_IConvertible_ToBoolean(IFormatProvider provider)
    {
        return false;
    }
}
```

- Verdict: ContextFail (method-not-found)
- Valid: True · Correct: False · IL fidelity: not currently checkable
- Commit: `ee13d4e2`

**After** (emitted C# at head `15e260fa` + verdict — verbatim harness compile-back
source): the interface is named in the base list, the target member is a real
explicit implementation with its original body, and every other required member
is a `throw null` explicit-interface stub so the surface satisfies CS0535:

```csharp
#pragma warning disable
using System;
public sealed class Convertible : IConvertible
{
    bool System.IConvertible.ToBoolean(IFormatProvider provider)
    {
        return false;
    }
    TypeCode System.IConvertible.GetTypeCode() { throw null; }
    char System.IConvertible.ToChar(IFormatProvider arg0) { throw null; }
    sbyte System.IConvertible.ToSByte(IFormatProvider arg0) { throw null; }
    byte System.IConvertible.ToByte(IFormatProvider arg0) { throw null; }
    short System.IConvertible.ToInt16(IFormatProvider arg0) { throw null; }
    ushort System.IConvertible.ToUInt16(IFormatProvider arg0) { throw null; }
    int System.IConvertible.ToInt32(IFormatProvider arg0) { throw null; }
    uint System.IConvertible.ToUInt32(IFormatProvider arg0) { throw null; }
    long System.IConvertible.ToInt64(IFormatProvider arg0) { throw null; }
    ulong System.IConvertible.ToUInt64(IFormatProvider arg0) { throw null; }
    float System.IConvertible.ToSingle(IFormatProvider arg0) { throw null; }
    double System.IConvertible.ToDouble(IFormatProvider arg0) { throw null; }
    decimal System.IConvertible.ToDecimal(IFormatProvider arg0) { throw null; }
    DateTime System.IConvertible.ToDateTime(IFormatProvider arg0) { throw null; }
    string System.IConvertible.ToString(IFormatProvider arg0) { throw null; }
    object System.IConvertible.ToType(Type arg0, IFormatProvider arg1) { throw null; }
}
```

- Verdict: Exact
- Valid: True · Correct: True · IL fidelity: True (target member round-trips to
  original opcodes)
- Commit: `15e260fa`

**Fully raised.** `The After render is in the fully raised state.` — the requested
target member (`ToBoolean`) reconstructs `Exact` and opcode-faithful. The
`throw null` stubs are intentional RTS scaffolding whose only role is to satisfy
the interface surface so the target's IL can be compiled and compared; they are
not a fidelity gap for the requested target.

## Scope and safety

- **Root cause:** Increment 1 gated engagement on the external interface's
  required surface being *exactly one* method (`requiredMethods.Count != 1` →
  decline). A multi-member interface therefore always declined to the sanitized
  floor even when every member was representable, because naming the interface in
  the base list demands the type implement all of them (CS0535).
- **Fix shape (harness orchestration only):** In
  `tools/DecompilerHarness/ReturnToSenderTypePlanner.cs`, relax the count gate to
  `== 0` (nothing to reconstruct) and find the single required method matching the
  target by name **and** generic arity **and** full decoded signature. For every
  other required member, synthesize a `CompileBackMemberRequirement`
  (`Kind=Method`, `StubBody=Throw`, `ExplicitInterfaceMemberName` +
  `DeclarationSignature`), reusing the exact explicit-interface emit path
  Increment 1 already validated (`throw null` body, verbatim declaration text).
  Stubs are appended to the reconstructed type's members.
- **Product impact:** None. No product source/printer/API changes; all new code is
  under `tools/DecompilerHarness/`.
- **Scope boundary (atomic + floor-first):** Engagement is whole-surface atomic.
  All pre-existing Increment-1 interface-level declines still fire in
  `TryCollectRequiredInterfaceMethods` (generic/property/event/non-public
  interface, non-public member, obsolete-error, `CompilerFeatureRequired`, generic
  method, varargs, and the `SignatureHasUnrepresentableDetail` probe covering
  by-ref/modifier/MDArray/function-pointer/`TypeSpec`), and each declines the
  **entire** surface — so a multi-member interface with any unspellable member
  declines atomically to the floor. A new stub-synthesis guard
  (`SynthesizeExternalInterfaceStub` / `SignatureTypeIsUnspellable`) additionally
  declines the whole engagement if any synthesized member has non-zero generic
  arity, a non-round-tripping name, or a decoded signature containing `+` (nested
  type) or `!` (a generic parameter that `CleanTypeDisplay` degrades to `object`).
- **RTS boundary:** RTS only orchestrates closure + Roslyn + contract-V1 body
  comparison; product/shared code owns C# source generation. The synthesized stubs
  reuse the existing product-owned explicit-interface member emit path unchanged.

## Evidence

| Check | Result |
| --- | --- |
| Product/harness build (`tools/DecompilerHarness -c Release`) | Pass (0 errors, 0 warnings) |
| Test build (`ILInspector.Decompiler.Tests -c Release`) | Pass (0 errors, 0 warnings) |
| Focused tests (`*External*`) | 37 total, 30 passed, 7 skipped (ilasm absent) |
| Full RTS class (`ReturnToSenderPrototypeTests`) | 184 total, 175 passed, 7 skipped, 2 pre-existing failures (#3251, unrelated) |
| Broad EVIL-corpus A/B | Not run in this environment (pinned corpus artifact unavailable on this Windows host, as for #3222); mechanism proven by focused round-trip tests |

New / changed focused tests
(`src/ILInspector.Decompiler.Tests/ReturnToSenderPrototypeTests.cs`):

- `CompileBackTargets_RoundTripsExternalMultiMemberExplicitInterfaceMethod` —
  `Convertible : IConvertible` (16 members), target
  `System.IConvertible.ToBoolean` → asserts **Exact**, base list + real explicit
  target + `throw null` sibling stub present, sanitized name absent. (Converted
  from the Increment-1 test that asserted the *decline*.)
- `CompileBackTargets_MultiMemberExternalExplicitInterfaceWithUnspellableSiblingFallsBackWithoutRecompileFail`
  — a representable target with a `ref int` **sibling** → the whole interface
  declines to the floor (not `RecompileFail`), proving whole-surface atomicity.
- `CompileBackTargets_MultiMemberExternalExplicitInterfaceWithOverloadedSiblingsRoundTrips`
  — same-name overloads (`Overloaded()` / `Overloaded(string)`, mirroring
  `ICustomTypeDescriptor.GetProperties`) emit as **distinct** explicit stubs (no
  name dedup) → **Exact**.

The `throw null` stubs are load-bearing: neutralizing stub emission (verified
locally) makes the positive test fail `CS0535: 'Convertible' does not implement
interface member 'IConvertible.GetTypeCode()'`, confirming the stubs are what
satisfy the surface and the positive test is a genuine regression guard.

## Frontiers and non-actions

| Item | Status | Reason |
| --- | --- | --- |
| Multi-member external **method-only** interfaces (`IConvertible`, method-only `ICustomTypeDescriptor` slice) | Fixed | Synthesize `throw null` stubs for the non-target members + name base list → Exact |
| External interfaces exposing **properties/events** (`ICollection`, property-bearing `ICustomTypeDescriptor` slice) | Left as frontier | `TryCollectRequiredInterfaceMethods` declines property/event-bearing interfaces; deferred (still safe: declines to floor) |
| Any member with by-ref / pointer / function-pointer / MDArray / `TypeSpec` / generic-method / varargs / non-public / obsolete-error detail | Declines atomically | Cannot spell confidently in a fresh compilation; whole interface reverts to the sanitized `ContextFail` floor |
| Nested (`+`) or generic-parameter (`!`) member signatures | Declines | `CleanTypeDisplay` would degrade them to `object`; rejected before emit |
| Generic external interfaces (`IEnumerable<T>`) | Not changed | Out of scope (unchanged from Increment 1) |
| `#3251` slow-gated RTS failures (`FullReconstructsPlainEventAccessorTarget`, `FirstPropertyGetter_EmitsClosureConstructorRequirement`) | Pre-existing / unrelated | Fail identically on base `ee13d4e2` (broken by #3129's `.ctor`→`__ctor` sanitizer); tracked in #3251 |

## Review

| Reviewer | Result | Notes |
| --- | --- | --- |
| GPT | Pending | Two-model review dispatched at head `15e260fa` |
| Gemini Pro | Pending | Two-model review dispatched at head `15e260fa` |

**Review conclusion:** **REVIEW** — high-risk (arbitrary external signature
translation with a floor-first safety invariant); two-model adversarial review in
progress. Reconciliation and `Ready to merge` to follow on the PR once both
fixed-head reviews are clean.

## Validation

```bash
dotnet build tools/DecompilerHarness/DecompilerHarness.csproj -c Release
dotnet build src/ILInspector.Decompiler.Tests/ILInspector.Decompiler.Tests.csproj -c Release
dotnet run --project src/ILInspector.Decompiler.Tests -c Release --no-build -- -method "*RoundTripsExternalMultiMemberExplicitInterfaceMethod*"
dotnet run --project src/ILInspector.Decompiler.Tests -c Release --no-build -- -method "*External*"
dotnet run --project src/ILInspector.Decompiler.Tests -c Release --no-build -- -class "ILInspector.Decompiler.Tests.ReturnToSenderPrototypeTests"
```

### CODE REVIEW

**Comment by richlander** [comment]
## Adversarial review — round 1 findings and resolution

Two-model review at head `15e260fa` (this is a high-risk change → two different models; I am Claude, so GPT + Gemini). Reviewers ran isolated on separate exact-head worktrees.

| Reviewer | Model | Round-1 result |
| --- | --- | --- |
| GPT | `gpt-5.6-sol` | 2 Advisory (both potential floor violations, not run through the harness) |
| Gemini Pro | `gemini-3.1-pro-preview` | 1 Critical (reproduced), 1 High (not reproducible) |

### Findings and resolution

**1. Base-interface member flattening → `RecompileFail` (BLOCKING; fixed).**
Found independently by both reviewers — Gemini as Critical (reproduced), GPT as Advisory. When an external interface inherits from another (`IDerived : IBase`), `TryCollectRequiredInterfaceMethods` flattened the base's members into the required surface without recording their declaring interface, so every synthesized stub was qualified with the *root* interface. An inherited member emitted as `void IDerived.Sibling()` is `CS0539` (not a member of `IDerived`) and leaves the base member unimplemented (`CS0535`) — a `ContextFail` → `RecompileFail` floor violation.

I reproduced it on the base head: target `RtsInh.IDerived.Target` with a sibling `RtsInh.IBase.Sibling` → `RecompileFail`, `CS0539: 'InhImpl.Sibling()' ... not found among members`, emitting `void RtsInh.IDerived.Sibling() { throw null; }`.

Fixed in `6279548b`: the base-interface recursion now declines the whole surface to the `ContextFail` floor whenever a base interface contributes a required member (an empty-marker base that adds nothing stays engaged). This preserves the intended `IConvertible` / `ICustomTypeDescriptor` targets (neither inherits). Regression test: `CompileBackTargets_InheritedBaseInterfaceMemberFallsBackWithoutRecompileFail`.

**2. `TypedReference` (`typedref`) member → `CS1599` (Advisory; fixed).**
GPT: a required member returning `typedref` survives the guards (`SignatureTypeIsUnspellable` only rejects `+`/`!`; the probe treated all primitives as representable) and emits a `TypedReference` return type, which C# rejects with `CS1599`. Reachable only from hand-authored / Reflection.Emit IL, not from any C#-compiled assembly.

Fixed in `6279548b`: `UnrepresentableSignatureProbe.GetPrimitiveType` now treats `PrimitiveTypeCode.TypedReference` as unrepresentable, so `SignatureHasUnrepresentableDetail` declines the whole surface (target and stubs). This matches the existing not-emittable-from-C# guards (`CompilerFeatureRequired`, obsolete-error). No Roslyn regression test is possible (a `typedref` return will not compile in a contracts assembly and `ilasm`/assembly-save is unavailable here); the guard is defense-in-depth, consistent with the other IL-only guards in this file.

**3. Nested external interface `+` separator → `CS1001` (Gemini High; dismissed with evidence).**
I could not reproduce this as a floor violation. On both base and fixed head, a nested external interface fixture (`RtsNest.Outer.IProbe`) returns `ContextFail` (sanitized floor `RtsNest_Outer_IProbe_Target`), **not** `RecompileFail`: `ExternalInterfaceReference` requires the interface `TypeReference` to resolve through an `AssemblyReference` scope (a nested type resolves through its enclosing `TypeReference`), and `ExternalInterfaceNameIsRepresentable` / `MetadataIdentifierRoundTrips` reject a `+`-bearing name segment. The reviewer's repro appears to have read the emitted decline text as a `RecompileFail`. I still added `CompileBackTargets_NestedExternalMultiMemberInterfaceFallsBackWithoutRecompileFail` to lock the floor, and asked the reviewer to re-run against `result.Status` on the fixed head.

### Validation of the fix (`6279548b`)

- Test build: Pass (0 warnings, warnings-as-errors)
- `*External*` + `*MultiMember*` + `*InheritedBaseInterfaceMember*` focused tests: pass
- Full `ReturnToSenderPrototypeTests`: 186 total / 177 pass / 7 skip (ilasm absent) / 2 pre-existing #3251 failures (unrelated, fail identically on base)

**Re-review of the fixed head `6279548b` is in progress on both models.** I will post `Ready to merge` only once both fixed-head re-reviews are clean.

**Comment by richlander** [comment]
## Adversarial review — re-review of fixed head clean

Both fixed-head re-reviews of `6279548b` came back **clean**.

| Reviewer | Model | Fixed-head (`6279548b`) result |
| --- | --- | --- |
| GPT | `gpt-5.6-sol` | CLEAN — no blocking findings |
| Gemini Pro | `gemini-3.1-pro-preview` | CLEAN — confirmed all fixes; retracted the nested-`+` finding as a false positive |

**Verified by both on the fixed head:**

- **Base-interface flattening (the blocking floor violation):** the whole surface now declines to the `ContextFail` floor whenever a base interface contributes any required member; empty-marker bases stay engaged; `IConvertible` / `ICustomTypeDescriptor` positives are unaffected and still reconstruct `Exact`. Gemini additionally confirmed member-bearing bases that would otherwise trip on a property/event/generic/unrepresentable member also decline cleanly through the inner collector.
- **`TypedReference` detail:** `typedref` in any return/parameter position now trips `SignatureHasUnrepresentableDetail` and declines the whole surface, averting `CS1599`; ordinary primitives are unaffected.
- **Nested external interface:** Gemini reproduced its own earlier finding as a false positive — nested interfaces never reach the `+` spelling because `ExternalInterfaceReference` requires an `AssemblyReference` resolution scope, so they already decline to the floor. Locked by a regression test.

**Merge-blocking status:**

- Product/harness + test build: Pass (0 warnings, warnings-as-errors)
- Full `ReturnToSenderPrototypeTests`: 186 total / 177 pass / 7 skip (ilasm absent) / 2 pre-existing #3251 failures (unrelated)
- CI `test (ubuntu-26.04, linux-x64)`: pass; path-gated jobs correctly skipped
- Branch contains `origin/main`; `MERGEABLE`

Ready to merge
