### PR TITLE
Emit the explicit version-1 identity from exact Type inspection

### PR DESCRIPTION
**Pull request by richlander**
**`main` does not build.** `dotnet build dotnet-inspect.slnx -c Release` at
`ca1a76df5` fails with four `CS0117` errors:

```text
src/DotnetInspector.Sections/ExactTypeInspectionOperation.cs(218,38): error CS0117:
  'InspectionDefinitionJson' does not contain a definition for 'CurrentSchemaVersion'
  (also 227, 236, 241)
```

## Cause

Two PRs that were each correct on their own base, and are not correct together:

- **#7075** (`ff3b6cc58`) removed `InspectionDefinitionJson.CurrentSchemaVersion`
  and replaced it with explicit `InspectionDefinitionSchema.Version1` and
  `Version2`. That was the point of the change: *"existing producers now
  deliberately emit v1 rather than following an ambiguous current-version
  constant."*
- **#6973** (`58655e223`) added `ExactTypeInspectionOperation.cs`, which
  constructs four definition records through the constant #7075 removed. It was
  written before #7075 landed and merged after it.

Both were green when they merged. Nothing rebuilt the pair.

## Fix

The four sites each construct a version-1 record, so each now says so —
the same spelling `WorkspaceSharePacketTransposer` already uses for its v1
producers. No behavior change: the schema version those records carry is
unchanged.

## Evidence

```text
$ dotnet build dotnet-inspect.slnx -c Release
Build succeeded.
    0 Error(s)

$ dotnet run --project tests/DotnetInspector.Sections.Tests -c Release
  total: 62, failed: 0

$ dotnet run --project tests/DotnetInspect.Cli.Tests -c Release -- --filter-class '*ExactTypeWorkspaceRoute*'
  total: 6, failed: 0
```

## Worth a follow-up

A merge that is green on its own base and red on the branch it lands on is not
detectable by any per-PR gate. GitHub's merge queue, or requiring branches to be
up to date before merging, would have caught this one.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01M3TJPCSxUCU7RKb2hyUW4a

### CODE REVIEW

**Comment by richlander** [comment]
Superseded by #7096, which landed the same repair while this was being written — the four sites now take a local `const int schemaVersion = InspectionDefinitionSchema.Version1;`, which reads better than repeating the constant. `main` builds again at `a850b66a4`; verified with a full `dotnet build dotnet-inspect.slnx -c Release`.

Closing unmerged. The follow-up thought stands on its own: a merge green on its own base and red on the branch it lands on is invisible to every per-PR gate, and this pair (#7075 removing `CurrentSchemaVersion`, #6973 still calling it) is the second instance I've hit today. A merge queue, or requiring a branch to be up to date before merge, is what catches that class.
