### PR TITLE
Pin native integer join coercion

### LINKED ISSUE #2334: CS0029/CS0173: nint/nuint join arms render bare (SameWidth null-width skips the reinterpret)
## Summary

`TryCoerceJoinArm`'s cross-signedness reinterpret branch is gated on `TypeFamilies.SameWidth(...)`, but `SameWidth` returns `false` for the platform-sized integers `nint`/`nuint` because `TypeFamilies.Width()` deliberately returns `null` for them. As a result a `nuint` arm at an `nint` join (or vice-versa) receives **no coercion** and renders bare, which does not compile (`CS0029`/`CS0173` — no implicit conversion between `nint` and `nuint`).

## Location

`src/ILInspector.Decompiler/Pipeline/Ir/CSharpPrinter.Numerics.cs` — `TryCoerceJoinArm` cross-signedness branch:

```csharp
if (target is { } numericTarget
    && TypeFamilies.NeedsNumericCast(EffectiveType(arm), numericTarget)
    && TypeFamilies.SameWidth(EffectiveType(arm), numericTarget))   // <-- false for nint/nuint
{
    ...
}
```

`TypeFamilies.Width()` returns `null` for `IntPtr`/`UIntPtr` (platform width unknown), so `SameWidth(nuint, nint) == false`; the branch is skipped and `TryCoerceJoinArm` returns `null`.

## Reproduced (decompiler product path, synthetic IR)

- Conditional `MergedType = nuint`, `c ? u : i` with `u: nuint`, `i: nint`.
- Probe printed: `needs=True sameWidth=False`.
- Rendered output: `c ? u : i` (bare).
- Compiler proof: `error CS0029: Cannot implicitly convert type 'nint' to 'nuint'`.

## Correct shape

```csharp
c ? u : (nuint)i
```
and, inside a checked region, the cast should be checked-safe (`unchecked((nuint)i)`).

## Suggested direction

`nint`↔`nuint` is a same-(platform-)width cross-signedness reinterpret exactly like the fixed-width sibling casts this branch already handles. Either treat platform-width pairs as same-width for this reinterpret (they always share a width at runtime), or add a dedicated native-int cross-signedness arm. Any cast added inside a checked region must route through `CheckedSafeCast` (`CheckedConversionCanThrow` currently answers `true` for platform-width — the safe direction).

## Provenance

- **Pre-existing**, not a regression: this `NeedsNumericCast && SameWidth` branch was introduced by #2310 and is byte-identical on `origin/main`; #2313 only reformats it.
- Found independently by **both** adversarial reviewers of #2313 (GPT-5.5 and Gemini 3.1 Pro); GPT-5.5 reproduced it through the decompiler product path.
- Relates to the umbrella #2095.
- Reachability on the real corpus is unverified (native-int conditional joins are rare); the code-path and compile failure are proven.

### PR DESCRIPTION
**Pull request by richlander**
- Fixes #2334
- Advances #2379 topic area 2
- Test-only closure for an issue fixed by the shared native-width conversion rule.
- Card revision: `ec4b3309`

## Change

**Conclusion:** **PASS** — current main already renders `nint`/`nuint` join arms with native cross-signedness reinterpret casts through `CSharpConversionRules.SameNumericSlotWidth`; this PR adds canaries in both directions so the old fixed-width `SameWidth` blind spot cannot return.

Before the underlying fix, these shapes rendered bare and did not compile:

```csharp
c ? u : i      // nuint target, nint arm
c ? i : u      // nint target, nuint arm
```

Pinned output now compiles:

```csharp
c ? u : (nuint)i
c ? i : (nint)u
```

## Evidence

| Check | Result |
| --- | --- |
| Focused tests | `CoerceChokePointTests` passed: 51/51 |
| Decompiler fast suite | Passed: 2,004/2,004 |
| Solution build | Passed |
| Render A/B / quality card | Not run: test-only PR, no product or docs changes |

## Review

Adversarial review pending: Gemini + MAI.

## Validation

```bash
dotnet restore src/ILInspector.Decompiler.Tests/ILInspector.Decompiler.Tests.csproj --configfile nuget.config --verbosity minimal
dotnet run --no-restore --project src/ILInspector.Decompiler.Tests -c Release -- -filter "/*/*/CoerceChokePointTests/*"
dotnet run --no-restore --project src/ILInspector.Decompiler.Tests -c Release -- -trait- "Speed=Slow"
dotnet restore dotnet-inspect.slnx --configfile nuget.config --verbosity minimal
dotnet build dotnet-inspect.slnx -c Release --no-restore --verbosity minimal
```

### CODE REVIEW

**Comment by richlander** [comment]
## Adversarial review reconciliation

Review status: **PASS, pending CI completion before Ready to merge**.

| Reviewer | Result | Notes |
| --- | --- | --- |
| MAI-Code-1-Flash | Clean after cleanup | Round 1 found no product gap and confirmed the initial canaries passed. Round 2 verified the duplicate `nuint`-target canary was removed, the existing `NativeIntegerJoinArm_ReinterpretsToMergedType` still covers that direction, and the remaining reverse-direction canary is valid and compile-asserted. |
| Gemini 3.1 Pro | Duplicate test finding resolved, then clean | Round 1 found that `NintArm_AtNuintMergedType_TakesNativeReinterpretCast` duplicated existing coverage. Commit 22333e10 removes it and keeps only the reverse `nint`-target canary. Round 2 verified test-only scope, the remaining canary's expected `c ? i : (nint)u` output, and no remaining checked/switch/coalesce product gap. |

Follow-up commit: 22333e10 (`Remove duplicate native join canary`).

Local validation after the follow-up remained clean: focused `CoerceChokePointTests` and decompiler fast suite. This PR is test-only, so no render A/B or quality card was required.
